version: '3.7'

services:
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      - POSTGRES_DB=${MEOWER_POSTGRES_NAME}
      - POSTGRES_PASSWORD=${MEOWER_POSTGRES_PASSWORD}
      - POSTGRES_USER=${MEOWER_POSTGRES_USERNAME}
    ports:
      - 5432:5432