version: '3.7'

services:
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      - POSTGRES_DB=${MEOWER_POSTGRES_NAME}
      - POSTGRES_PASSWORD=${MEOWER_POSTGRES_PASSWORD}
      - POSTGRES_USER=${MEOWER_POSTGRES_USERNAME}
    ports:
      - ${MEOWER_POSTGRES_PORT}:${MEOWER_POSTGRES_PORT}
  nats:
    image: "nats-streaming:latest"
    restart: "always"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.11.1"