version: '3.7'

services:
  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
    depends_on:
      - "meow"
      - "query"
      - "pusher"
  meow:
    build: 
      context: "."
      dockerfile: "/meow_service/Dockerfile"
    command: "meow-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - ${MEOWER_PORT}:${MEOWER_PORT}
    env_file:
      - .env
  query:
    build: 
      context: "."
      dockerfile: "/query_service/Dockerfile"
    command: "query-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - ${MEOWER_PORT}:${MEOWER_PORT}
    env_file:
      - .env
  pusher:
    build:
      context: "."
      dockerfile: "/pusher_service/Dockerfile"
    command: "pusher-service"
    depends_on:
      - "nats"
    ports:
      - ${MEOWER_PORT}:${MEOWER_PORT}
    env_file:
      - .env
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      - POSTGRES_DB=${MEOWER_POSTGRES_NAME}
      - POSTGRES_PASSWORD=${MEOWER_POSTGRES_PASSWORD}
      - POSTGRES_USER=${MEOWER_POSTGRES_USERNAME}
    ports:
      - ${MEOWER_POSTGRES_PORT}:${MEOWER_POSTGRES_PORT}
  nats:
    image: "nats-streaming:latest"
    restart: "always"
    ports:
      - ${MEOWER_NATS_PORT}:${MEOWER_NATS_PORT}
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.11.1"
    ports:
      - ${MEOWER_ELASTICSEARCH_PORT}:${MEOWER_ELASTICSEARCH_PORT}