version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: "always"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${MEOWER_POSTGRES_NAME}
      - POSTGRES_PASSWORD=${MEOWER_POSTGRES_PASSWORD}
      - POSTGRES_USER=${MEOWER_POSTGRES_USERNAME}
    volumes:
      - ./schema:/docker-entrypoint-initdb.d